[build]
  publish = "frontend"

[[edge_functions]]
  path = "/api/*"
  function = "api-proxy"

[[redirects]]
  from = "/lesson"
  to = "/lesson.html"
  status = 200

[[redirects]]
  from = "/auth"
  to = "/auth.html"
  status = 200

[[redirects]]
  from = "/account"
  to = "/account.html"
  status = 200

[[redirects]]
  from = "/news"
  to = "/news.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/faq.html"
  status = 200
